### ISSUE TITLE
There's a weird copy of this repo?

### ISSUE THREAD

**Issue by alecmocatta** [FuzzrNet/Forage#6]
The user [@bejolithic](https://github.com/bejolithic) ("Bejolithic <human@bejolithic.tech>") seems to have made a replica of this repo? It's been cleansed of attribution, from a brief look.

See [https://github.com/nervive/maimo](https://github.com/nervive/maimo/tree/6d1610a3eac0541f3c998552e44c16b412791eb8) and [https://crates.io/crates/maimo](https://crates.io/crates/maimo/0.0.3).

**Comment by kn0wmad** [comment]
Wtf, that's weird... Why wouldn't the user make a fork and give attribution?  Granted the license allows for this behavior, but it's kind of a dick move if they intend to pretend they created it all.  @bejolithic care to comment?

**Comment by cryptoquick** [comment]
It looks like their GitHub account was taken down? Very bizarre. I'm not too worried about it, though. I chose the public domain license specifically because I worry more about suppression and censorship than I do about impersonation or whitelabeled unattributed copies. But I guess your Apache license didn't deter them, either. :man_shrugging: 

Regardless, thanks for letting me know, and if you find anything else out, I'd be curious what the deal was behind all of this.
